### ISSUE TITLE
Refactoring for new versions of Godot and documenting it

### ISSUE THREAD

**Issue by samyarkd** [TuysuzTavsan/GodotMultiplayerDemo#1]
I'm learning Godot so if you want i can create a PR and apply changes with comments inside the code. otherwise, you can close this issue.

**Comment by TuysuzTavsan** [comment]
Hey, what kind of changes you want to make? Project is fragile in many ways and a lot of stuff is hard coded to demonstrate example.

**Comment by samyarkd** [comment]
just adding comments so next time someone tries to use it will be easier to understand, also making some simple helper function. and updating the Webrtc implementation in probably 2 places first updating library and second changing a Class name from `WebRtclibPeerConnection` to `WebRtcPeerConnection`

**Comment by TuysuzTavsan** [comment]
Comments and changing code if needed to upgrade current stable godot version is ok. Also changing webrtc lib to match updated version is understandable. But making any changes to webrtc library is not desired. It should match the released original version. You should make your desired changes about library on its godot-webrtc repo page. However I dont promise anything.
